backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean", default: false }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: "Hero",
              name: "hero",
              widget: "object",
              fields:
                [
                  { label: Title, name: title, widget: string, required: false },
                  { label: Subheading, name: subheading, widget: string, required: false },
                  { label: Logo, name: logo, widget: image },
                  { label: Background Image, name: backgroundImage, widget: image },
                ]
            }
          - {
              label: MainPitch,
              name: mainPitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string, required: false },
                  { label: Description, name: description, widget: text },
                ],
            }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Blurbs,
              name: blurbs,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string, required: false },
                  { label: Text, name: text, widget: text },
                  { label: Image, name: image, widget: image },
                ],
            }
      # - file: "src/pages/about/index.md"
      #   label: "About"
      #   name: "about"
      #   fields:
      #     - {
      #         label: "Template Key",
      #         name: "templateKey",
      #         widget: "hidden",
      #         default: "about-page",
      #       }
      #     - { label: "Title", name: "title", widget: "string" }
      #     - { label: "Body", name: "body", widget: "markdown" }
      # - file: "src/pages/products/index.md"
      #   label: "Products Page"
      #   name: "products"
      #   fields:
      #     - {
      #         label: "Template Key",
      #         name: "templateKey",
      #         widget: "hidden",
      #         default: "product-page",
      #       }
      #     - { label: Title, name: title, widget: string }
      #     - { label: Image, name: image, widget: image }
      #     - { label: Heading, name: heading, widget: string }
      #     - { label: Description, name: description, widget: string }
      #     - {
      #         label: Intro,
      #         name: intro,
      #         widget: object,
      #         fields:
      #           [
      #             { label: Heading, name: heading, widget: string },
      #             { label: Description, name: description, widget: text },
      #             {
      #               label: Blurbs,
      #               name: blurbs,
      #               widget: list,
      #               fields:
      #                 [
      #                   { label: Image, name: image, widget: image },
      #                   { label: Text, name: text, widget: text },
      #                 ],
      #             },
      #           ],
      #       }
      #     - {
      #         label: Main,
      #         name: main,
      #         widget: object,
      #         fields:
      #           [
      #             { label: Heading, name: heading, widget: string },
      #             { label: Description, name: description, widget: text },
      #             {
      #               label: Image1,
      #               name: image1,
      #               widget: object,
      #               fields:
      #                 [
      #                   { label: Image, name: image, widget: image },
      #                   { label: Alt, name: alt, widget: string },
      #                 ],
      #             },
      #             {
      #               label: Image2,
      #               name: image2,
      #               widget: object,
      #               fields:
      #                 [
      #                   { label: Image, name: image, widget: image },
      #                   { label: Alt, name: alt, widget: string },
      #                 ],
      #             },
      #             {
      #               label: Image3,
      #               name: image3,
      #               widget: object,
      #               fields:
      #                 [
      #                   { label: Image, name: image, widget: image },
      #                   { label: Alt, name: alt, widget: string },
      #                 ],
      #             },
      #           ],
      #       }
      #     - {
      #         label: Testimonials,
      #         name: testimonials,
      #         widget: list,
      #         fields:
      #           [
      #             { label: Quote, name: quote, widget: string },
      #             { label: Author, name: author, widget: string },
      #           ],
      #       }
      #     - { label: Full_image, name: full_image, widget: image }
      #     - {
      #         label: Pricing,
      #         name: pricing,
      #         widget: object,
      #         fields:
      #           [
      #             { label: Heading, name: heading, widget: string },
      #             { label: Description, name: description, widget: string },
      #             {
      #               label: Plans,
      #               name: plans,
      #               widget: list,
      #               fields:
      #                 [
      #                   { label: Plan, name: plan, widget: string },
      #                   { label: Price, name: price, widget: string },
      #                   {
      #                     label: Description,
      #                     name: description,
      #                     widget: string,
      #                   },
      #                   { label: Items, name: items, widget: list },
      #                 ],
      #             },
      #           ],
      #       }
  - name: "settings"
    label: "Settings"
    files:
      - file: "src/settings/header.yml"
        label: "Header"
        name: "header"
        editor:
          preview: false
        fields:
          - { label: Logo, name: logoImage, widget: image }
          - { label: "Menu Items",
              label_singular: "Add menu item",
              name: "menuItems",
              widget: "list",
              fields:
                [
                  { label: Label, name: label, widget: string },
                  { label: Url, name: url, widget: string },
                  { label: Open In New Tab, name: external, widget: boolean, default: false },
                ]
            }
          - { label: "Call To Action",
              name: "cta",
              widget: "object",
              fields:
                [
                  { label: Label, name: label, widget: string },
                  { label: Url, name: url, widget: string },
                  { label: Open In New Tab, name: external, widget: boolean, default: false },
                ]
            }
      - file: "src/settings/footer.yml"
        label: "Footer"
        name: "footer"
        editor:
          preview: false
        fields:
          - { label: Logo, name: logoImage, widget: image }
          - { label: "Left Menu",
              label_singular: "Add menu item",
              name: "leftMenuItems",
              widget: "list",
              fields:
                [
                  { label: Label, name: label, widget: string },
                  { label: Url, name: url, widget: string },
                  { label: Open In New Tab, name: external, widget: boolean, default: false },
                ]
            }
          - { label: "Right Menu",
              label_singular: "Add menu item",
              name: "rightMenuItems",
              widget: "list",
              fields:
                [
                  { label: Label, name: label, widget: string },
                  { label: Url, name: url, widget: string },
                  { label: Open In New Tab, name: external, widget: boolean, default: false },
                ]
            }
          - { label: "Icons",
              label_singular: "Add icon",
              name: "icons",
              widget: "list",
              fields:
                [
                  {
                    label: Icon,
                    name: id,
                    widget: select,
                    options: [
                      { label: "Twitter", value: "twitter" },
                      { label: "Youtube", value: "youtube" },
                    ]
                  },
                  { label: Url, name: url, widget: string },
                  { label: Open In New Tab, name: external, widget: boolean, default: false },
                ]
            }